AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:

  ThaiLandFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.thaiLand
      Runtime: nodejs14.x
      CodeUri: . 
      Events:
        Trigger:
          Type: CloudWatchEvent 
          Properties:
            Pattern:
              source:
                - custom.orderManager
              detail-type:
                - order                
              detail:
                restaurantName:
                  - "thaiLand"